GRANT USAGE ON DATABASE {{ db_name }} TO ROLE CICD_DEMO_DATA_ENGINEER;
GRANT USAGE ON DATABASE {{ db_name }} TO ROLE CICD_DEMO_DATA_ANALYST;
GRANT USAGE ON DATABASE {{ db_name }} TO ROLE CICD_DEMO_DEPLOYER;

GRANT ALL ON SCHEMA {{ db_name }}.RAW TO ROLE CICD_DEMO_DATA_ENGINEER;
GRANT ALL ON SCHEMA {{ db_name }}.TRANSFORMED TO ROLE CICD_DEMO_DATA_ENGINEER;
GRANT USAGE ON SCHEMA {{ db_name }}.PRESENTATION TO ROLE CICD_DEMO_DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA {{ db_name }}.PRESENTATION TO ROLE CICD_DEMO_DATA_ANALYST;

GRANT USAGE ON WAREHOUSE CICD_DEMO_WH_{{ env }} TO ROLE CICD_DEMO_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE CICD_DEMO_WH_{{ env }} TO ROLE CICD_DEMO_DATA_ANALYST;
