DEFINE ROLE CICD_DEMO_DATA_ENGINEER;
DEFINE ROLE CICD_DEMO_DATA_ANALYST;
DEFINE ROLE CICD_DEMO_DEPLOYER;

GRANT ROLE CICD_DEMO_DATA_ENGINEER TO ROLE CICD_DEMO_DEPLOYER;
GRANT ROLE CICD_DEMO_DATA_ANALYST TO ROLE CICD_DEMO_DEPLOYER;

{% for e in environments %}
GRANT USAGE ON DATABASE {{ e.db_name }} TO ROLE CICD_DEMO_DATA_ENGINEER;
GRANT USAGE ON DATABASE {{ e.db_name }} TO ROLE CICD_DEMO_DATA_ANALYST;
GRANT USAGE ON DATABASE {{ e.db_name }} TO ROLE CICD_DEMO_DEPLOYER;

GRANT ALL ON SCHEMA {{ e.db_name }}.RAW TO ROLE CICD_DEMO_DATA_ENGINEER;
GRANT ALL ON SCHEMA {{ e.db_name }}.TRANSFORMED TO ROLE CICD_DEMO_DATA_ENGINEER;
GRANT USAGE ON SCHEMA {{ e.db_name }}.PRESENTATION TO ROLE CICD_DEMO_DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA {{ e.db_name }}.PRESENTATION TO ROLE CICD_DEMO_DATA_ANALYST;

GRANT USAGE ON WAREHOUSE CICD_DEMO_WH_{{ e.env }} TO ROLE CICD_DEMO_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE CICD_DEMO_WH_{{ e.env }} TO ROLE CICD_DEMO_DATA_ANALYST;
{% endfor %}
